name: CI

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Validate commit messages
        run: npx commitlint --from=HEAD~10 --to=HEAD
     
      - name: Run tests
        run: npm test

  